syntax on
set number
set spell
set tabstop=4
set shiftwidth=4
set expandtab
set nobackup
set noswapfile
set nowritebackup
set cursorline
set undolevels=1000
set updatetime=300
set shortmess+=c
set signcolumn=yes
